### ISSUE TITLE
There is no documentation how to extract postcode data from a string

### ISSUE THREAD

**Issue by gajus** [pjlsergeant/ziprip#1]
There is no documentation how to extract postcode data from a string.

Looking at a test case, it doesn't even look that there is a method to do that exposed via the public API.

https://github.com/sheriff/ziprip/blob/master/test/040_addressFromString.js

**Comment by pjlsergeant** [comment]
That's correct - the library isn't designed to extract from strings, it's designed to extract from DOM objects, including looking for various ways addresses might be embedded in a DOM.

String to address is a fallback, and implemented here: https://github.com/sheriff/ziprip/blob/master/src/addressFromString.js

It should be easy enough to wrap that file.
