### ISSUE TITLE
Using ziprip on variable in nodejs

### ISSUE THREAD

**Issue by DavidFH** [pjlsergeant/ziprip#2]
Hello,

Is there a way to use ziprip on the server side. I have a variable containing a string which I would like to search through for any present addresses and store them in a separate array. Is there functionality in this module to do as described?

Kind Regards

**Comment by pjlsergeant** [comment]
https://github.com/pjlsergeant/ziprip/blob/master/src/addressFromString.js#L14

That function will do it. You will need to pass it an object with `addressFromFields` set to https://github.com/pjlsergeant/ziprip/blob/master/src/cleanAddress_en.js#L8 as `toolkit`

**Comment by DavidFH** [comment]
Thank you, will give this a go now.

**Comment by DavidFH** [comment]
Have tried using:

var test = ziprip.addressFromString({addressFromFields: ziprip.cleanAddress}, page.text);

Did not return anything and paused my code execution. Any other suggestions?

Kind Regards

**Comment by teebu** [comment]
```
var toolkit = require('./src/address.js');
var addressFromString = require('./src/addressFromString')


var test = addressFromString.addressFromString( toolkit, '601 Sherwood Ave. San Bernardino, CA 92404.')

console.log(test)
```
