### ISSUE TITLE
Documentation is lacking when getting started (easily) in node JS and JSDOM

### ISSUE THREAD

**Issue by charliemitchell** [pjlsergeant/ziprip#3]
Hello. 
It is not very clear what should be passed into ziprip when using node js and jsdom.
Can you update your README to be more specific about this. Example...
# Usage

_ziprip_ has one method you should be interested in: `extract`, which accepts a _DOM object_ and a _URL_. For _node.js_ you can use [jsdom](https://github.com/tmpvar/jsdom/) and pass in jsdom's environment.document (window.document), and in the browser obviously you just pass in `document`.

**node.js**

```
var $ziprip = require('ziprip');
var jsdom = require('jsdom');
var url = 'http://www.a-website.com';
var addresses;

jsdom.env(
   url,
    function (error, window) {
        var addresses = $ziprip.extract( window.document, url );
    }
);
```

Essentially, the README is a little confusing for the Node implementation. Are you supposed to pass in the JSDOM Class, the jsdom environment object, maybe window.$. Does passing in window.document.getElementByID("foo") work?  The confusion could be from stating that you pass in a DOM object, but what I think you mean is that you need to pass in `The document object`. There are many DOM objects in the DOM, but I'm assuming that the document object is the only one that works given the calls to document.createElement etc...

In any case, I was able to get it up and running, and I appreciate your work here. ZipRip is very useful, and I believe with a little more of your attention on your README file more people like myself can benefit from your work.

**Comment by prashantgpt91** [comment]
the script you mentioned above gives null output?
i had used the same script on http://www.mahuagallery.com/

here it is 

```
var $ziprip = require('ziprip');
var jsdom = require('jsdom');
var url = 'http://www.mahuagallery.com/';
var addresses;

jsdom.env(
   url,
    function (error, window) {
        addresses = $ziprip.extract( window.document, url );
        console.log("here's the result");
        console.log(addresses); 
    }
);

```

**Comment by charliemitchell** [comment]
No, the script above works fine. The suggestion is to modify the usage section for node to include the excerpt above. Currently the usage for node takes in domObject as a parameter, but it doesn't state what that variable is.

**Comment by charliemitchell** [comment]
I.E. What is domObject? It may be confusing because there are many DOM Objects to choose from. But what you want is the actual document Object not a DOM Object.
